V1
reside-ic/reboot-monitor pull request #1
Opened 2020-09-15 10:29 UTC by weshinsley

2020-09-22 15:19 UTC, richfitz requested changes
I know you have a soft spot for php, but I wonder if this might be easier to maintain as a flask app (python). Any thoughts about translating this into that? It would not be a huge amount of work, but is then much easier to test, plus we get to use requests for the ping to teams which is a bit nicer

2020-09-23 08:08 UTC, weshinsley commented
Not sure if flask plays well with Xampp/Apache on Windows where this is currently living.... I've not tried, just I've read reports that it's a once in a lifetime experience....

2020-11-12 17:20 UTC, weshinsley commented
Now reimplemented as a flask app in python...

2020-11-12 18:02 UTC, richfitz requested changes
I am mostly a bit confused about the amount of logic here and would like to see if we can reduce it a bit - I wonder if that interacts with the deployment issue? this looks like something that is trying to stay up for ages while the data around it changes, but the docker approach of something fairly ephemeral might eliminate much of that

2020-11-12 18:02 UTC, richfitz commented on monitor.py
> +    return redirect("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
Wes, this is a side of you I would never have guessed

2020-11-12 18:02 UTC, richfitz commented on monitor.py
> +                    csvfile.close()
should these be done with python's usual `with ... as ...:` style? Most resource acquisition in python is done that way now

2020-11-12 18:02 UTC, richfitz commented on monitor.py
> +                if ((grey_machine == given_machine) and (grey_ip == given_ip)):
(throughout) - no paraens in a python if statement

2020-11-12 18:02 UTC, richfitz commented on monitor.py
> +def check_greylist(grey_list, given_machine, given_ip):
I can't immediately understand the algorithm here here, or why so many files are read (presumably on each call?)

2020-11-12 18:02 UTC, richfitz commented on monitor.py
> +    ensure_exists(data_lock_file, "lock")
I'm not sure why lockfiles are needed here? why is this information changing?

2020-11-12 22:13 UTC, weshinsley commented on monitor.py
> +    ensure_exists(data_lock_file, "lock")
It's becuase (I believe...) the Win Apache can launch multiple threads concurrently into the flask app code, so I want to make the changes to the CSVs atomic, should cron.daily decide that multiple machines make the call at the same time. It's an outshot I know...

2020-11-12 22:15 UTC, weshinsley commented on monitor.py
> +    return redirect("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
If people want to browse willy-nilly to a server that's not meant to browsed to, they can get what's coming to them...

2020-11-12 22:25 UTC, weshinsley commented on monitor.py
> +def check_greylist(grey_list, given_machine, given_ip):
Basically, I don't really want the hassle of different nodes having to authenticate or look anything up.

1) I have a whitelist of {machine,ip} - and if the name presented by the machine, and the ip detected from the request match a whitelist entry, that's good enough for me.

2) The greylist is then a bit of a luxury/curiosity - it logs {machine,ip} of requests not on the whitelist, so I can easily copy/paste the line over, or see who's managed at least to guess the GET parameters and spammed us.

2020-11-12 22:32 UTC, weshinsley commented
There's nothing deployment specific affecting the code/logic here - probably I haven't quite got the pattern for flask apps - I am thinking in an atomic CGI sort of way (lock the files, update the files, release the files), and perhaps that's not quite the flask way...

2020-11-12 22:40 UTC, weshinsley commented on monitor.py
> +                    csvfile.close()
Possibly - it's not a syntax I know yet...

2020-11-13 10:43 UTC, weshinsley commented on monitor.py
> +                if ((grey_machine == given_machine) and (grey_ip == given_ip)):
Fixed

2022-03-01 19:50 UTC, richfitz requested changes
will review the rest later, but just saw this....

2022-03-01 19:50 UTC, richfitz commented on secret/report.py
> +team_webhook = "https://imperiallondon.webhook.office.com/webhookb2/" \
This is a secret, no? Should come from vault I'd have thought (and we may want to regenerate this one now)

2022-04-28 08:59 UTC, weshinsley commented on secret/report.py
> +team_webhook = "https://imperiallondon.webhook.office.com/webhookb2/" \
Oops - regenerated. This is still running as Flask-App compiled into Apache on Win/Xampp at the moment, and the report called with a scheduled task, so further work to be done (if worth it) on getting the key from vault - or making this into a more conventional flask app.

2026-06-09 13:05 UTC, weshinsley commented
No longer relevant

2026-06-09 13:05 UTC, closed without merging